name: CI Build
on:
  push:
    paths:
      - '**/*.spec'
jobs:
  list:
    name: List packages to build
    runs-on: [ubuntu-latest]
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Get changed files for master branch
        if: github.ref == 'refs/heads/master'
        id: getfile
        uses: jitterbit/get-changed-files@v1
      - name: Get changed files for branch
        if: github.ref != 'refs/heads/master'
        id: getfile
        run: |
          echo "::set-output name=all::$(git diff-tree --no-commit-id --name-only -r ${{ github.sha }}| xargs)"
      - name: Build output based on the changed files
        id: packages
        run: |
          echo "::set-output name=packages::$(l=1; A=(${{ steps.getfile.outputs.all }}); size=${#A[@]}; echo -n "["; for i in ${A[@]}; do dir=$(dirname $i); echo -n \"$dir\"; if [ $l -lt $size ]; then echo -n ","; let "l = l + 1"; fi; done; echo "]";)"
    outputs:
     matrix: ${{ steps.packages.outputs.packages }}
  test_and_build:
    needs: list
    name: CI and send to Copr
    strategy:
      matrix:
        packages: ${{ fromJson(needs.list.outputs.matrix) }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out proper version of sources
        uses: actions/checkout@v1
      - name: Sanity build of the rpm package from ${{ matrix.packages }}
        working-directory: ${{ matrix.packages }}
        run: |
          docker run -v ${PWD}:/sources -v ${PWD}:/output:Z quay.io/abn/rpmbuilder:centos-7
      - name: Build the srpm package from ${{ matrix.packages }}
        working-directory: ${{ matrix.packages }}
        run: |
          docker run -v ${PWD}:/sources -v ${PWD}:/output:Z -e "SRPM_ONLY=1" quay.io/abn/rpmbuilder:centos-7

